name: VPS Deploy CI
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PythonコードをVPSに自動デプロイ
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SECRET_KEY }}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd src/django-auto-deploy
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python3 main.py
            deactivate
